
# -*- coding, utf-8 -*-
from __future__ import unicode_literals


from django.utils.translation import ugettext_lazy as _



COUNTRIES = (
    ("",   _("Please select") ),
    ("AFG", _("Afghanistan") ),
    ("ALA", _("Aland Islands") ),
    ("ALB", _("Albania") ),
    ("DZA", _("Algeria") ),
    ("ASM", _("American Samoa") ),
    ("AND", _("Andorra") ),
    ("AGO", _("Angola") ),
    ("AIA", _("Anguilla") ),
    ("ATA", _("Antarctica") ),
    ("ATG", _("Antigua and Barbuda") ),
    ("ARG", _("Argentina") ),
    ("ARM", _("Armenia") ),
    ("ABW", _("Aruba") ),
    ("AUS", _("Australia") ),
    ("AUT", _("Austria") ),
    ("AZE", _("Azerbaijan") ),
    ("BHS", _("Bahamas") ),
    ("BHR", _("Bahrain") ),
    ("BGD", _("Bangladesh") ),
    ("BRB", _("Barbados") ),
    ("BLR", _("Belarus") ),
    ("BEL", _("Belgium") ),
    ("BLZ", _("Belize") ),
    ("BEN", _("Benin") ),
    ("BMU", _("Bermuda") ),
    ("BTN", _("Bhutan") ),
    ("BOL", _("Bolivia, Plurinational State of") ),
    ("BES", _("Bonaire, Sint Eustatius and Saba") ),
    ("BIH", _("Bosnia and Herzegovina") ),
    ("BWA", _("Botswana") ),
    ("BVT", _("Bouvet Island") ),
    ("BRA", _("Brazil") ),
    ("IOT", _("British Indian Ocean Territory") ),
    ("BRN", _("Brunei Darussalam") ),
    ("BGR", _("Bulgaria") ),
    ("BFA", _("Burkina Faso") ),
    ("BDI", _("Burundi") ),
    ("KHM", _("Cambodia") ),
    ("CMR", _("Cameroon") ),
    ("CAN", _("Canada") ),
    ("CPV", _("Cape Verde") ),
    ("CYM", _("Cayman Islands") ),
    ("CAF", _("Central African Republic") ),
    ("TCD", _("Chad") ),
    ("CHL", _("Chile") ),
    ("CHN", _("China") ),
    ("CXR", _("Christmas Island") ),
    ("CCK", _("Cocos (Keeling) Islands") ),
    ("COL", _("Colombia") ),
    ("COM", _("Comoros") ),
    ("COG", _("Congo") ),
    ("COD", _("Congo, the Democratic Republic of the") ),
    ("COK", _("Cook Islands") ),
    ("CRI", _("Costa Rica") ),
    ("CIV", _("Cote d'Ivoire") ),
    ("HRV", _("Croatia") ),
    ("CUB", _("Cuba") ),
    ("CUW", _("Curacao") ),
    ("CYP", _("Cyprus") ),
    ("CZE", _("Czech Republic") ),
    ("DNK", _("Denmark") ),
    ("DJI", _("Djibouti") ),
    ("DMA", _("Dominica") ),
    ("DOM", _("Dominican Republic") ),
    ("ECU", _("Ecuador") ),
    ("EGY", _("Egypt") ),
    ("SLV", _("El Salvador") ),
    ("GNQ", _("Equatorial Guinea") ),
    ("ERI", _("Eritrea") ),
    ("EST", _("Estonia") ),
    ("ETH", _("Ethiopia") ),
    ("FLK", _("Falkland Islands (Malvinas)") ),
    ("FRO", _("Faroe Islands") ),
    ("FJI", _("Fiji") ),
    ("FIN", _("Finland") ),
    ("FRA", _("France") ),
    ("GUF", _("French Guiana") ),
    ("PYF", _("French Polynesia") ),
    ("ATF", _("French Southern Territories") ),
    ("GAB", _("Gabon") ),
    ("GMB", _("Gambia") ),
    ("GEO", _("Georgia") ),
    ("DEU", _("Germany") ),
    ("GHA", _("Ghana") ),
    ("GIB", _("Gibraltar") ),
    ("GRC", _("Greece") ),
    ("GRL", _("Greenland") ),
    ("GRD", _("Grenada") ),
    ("GLP", _("Guadeloupe") ),
    ("GUM", _("Guam") ),
    ("GTM", _("Guatemala") ),
    ("GGY", _("Guernsey") ),
    ("GIN", _("Guinea") ),
    ("GNB", _("Guinea-Bissau") ),
    ("GUY", _("Guyana") ),
    ("HTI", _("Haiti") ),
    ("HMD", _("Heard Island and McDonald Islands") ),
    ("VAT", _("Holy See (Vatican City State)") ),
    ("HND", _("Honduras") ),
    ("HKG", _("Hong Kong") ),
    ("HUN", _("Hungary") ),
    ("ISL", _("Iceland") ),
    ("IND", _("India") ),
    ("IDN", _("Indonesia") ),
    ("IRN", _("Iran, Islamic Republic of") ),
    ("IRQ", _("Iraq") ),
    ("IRL", _("Ireland") ),
    ("IMN", _("Isle of Man") ),
    ("ISR", _("Israel") ),
    ("ITA", _("Italy") ),
    ("JAM", _("Jamaica") ),
    ("JPN", _("Japan") ),
    ("JEY", _("Jersey") ),
    ("JOR", _("Jordan") ),
    ("KAZ", _("Kazakhstan") ),
    ("KEN", _("Kenya") ),
    ("KIR", _("Kiribati") ),
    ("PRK", _("Korea, Democratic People's Republic of") ),
    ("KOR", _("Korea, Republic of") ),
    ("KWT", _("Kuwait") ),
    ("KGZ", _("Kyrgyzstan") ),
    ("LAO", _("Lao People's Democratic Republic") ),
    ("LVA", _("Latvia") ),
    ("LBN", _("Lebanon") ),
    ("LSO", _("Lesotho") ),
    ("LBR", _("Liberia") ),
    ("LBY", _("Libya") ),
    ("LIE", _("Liechtenstein") ),
    ("LTU", _("Lithuania") ),
    ("LUX", _("Luxembourg") ),
    ("MAC", _("Macao") ),
    ("MKD", _("Macedonia, the former Yugoslav Republic of") ),
    ("MDG", _("Madagascar") ),
    ("MWI", _("Malawi") ),
    ("MYS", _("Malaysia") ),
    ("MDV", _("Maldives") ),
    ("MLI", _("Mali") ),
    ("MLT", _("Malta") ),
    ("MHL", _("Marshall Islands") ),
    ("MTQ", _("Martinique") ),
    ("MRT", _("Mauritania") ),
    ("MUS", _("Mauritius") ),
    ("MYT", _("Mayotte") ),
    ("MEX", _("Mexico") ),
    ("FSM", _("Micronesia, Federated States of") ),
    ("MDA", _("Moldova, Republic of") ),
    ("MCO", _("Monaco") ),
    ("MNG", _("Mongolia") ),
    ("MNE", _("Montenegro") ),
    ("MSR", _("Montserrat") ),
    ("MAR", _("Morocco") ),
    ("MOZ", _("Mozambique") ),
    ("MMR", _("Myanmar") ),
    ("NAM", _("Namibia") ),
    ("NRU", _("Nauru") ),
    ("NPL", _("Nepal") ),
    ("NLD", _("Netherlands") ),
    ("NCL", _("New Caledonia") ),
    ("NZL", _("New Zealand") ),
    ("NIC", _("Nicaragua") ),
    ("NER", _("Niger") ),
    ("NGA", _("Nigeria") ),
    ("NIU", _("Niue") ),
    ("NFK", _("Norfolk Island") ),
    ("MNP", _("Northern Mariana Islands") ),
    ("NOR", _("Norway") ),
    ("OMN", _("Oman") ),
    ("PAK", _("Pakistan") ),
    ("PLW", _("Palau") ),
    ("PSE", _("Palestinian Territory, Occupied") ),
    ("PAN", _("Panama") ),
    ("PNG", _("Papua New Guinea") ),
    ("PRY", _("Paraguay") ),
    ("PER", _("Peru") ),
    ("PHL", _("Philippines") ),
    ("PCN", _("Pitcairn") ),
    ("POL", _("Poland") ),
    ("PRT", _("Portugal") ),
    ("PRI", _("Puerto Rico") ),
    ("QAT", _("Qatar") ),
    ("REU", _("Reunion") ),
    ("ROU", _("Romania") ),
    ("RUS", _("Russian Federation") ),
    ("RWA", _("Rwanda") ),
    ("BLM", _("Saint Barthelemy") ),
    ("SHN", _("Saint Helena, Ascension and Tristan da Cunha") ),
    ("KNA", _("Saint Kitts and Nevis") ),
    ("LCA", _("Saint Lucia") ),
    ("MAF", _("Saint Martin (French part)") ),
    ("SPM", _("Saint Pierre and Miquelon") ),
    ("VCT", _("Saint Vincent and the Grenadines") ),
    ("WSM", _("Samoa") ),
    ("SMR", _("San Marino") ),
    ("STP", _("Sao Tome and Principe") ),
    ("SAU", _("Saudi Arabia") ),
    ("SEN", _("Senegal") ),
    ("SRB", _("Serbia") ),
    ("SYC", _("Seychelles") ),
    ("SLE", _("Sierra Leone") ),
    ("SGP", _("Singapore") ),
    ("SXM", _("Sint Maarten (Dutch part)") ),
    ("SVK", _("Slovakia") ),
    ("SVN", _("Slovenia") ),
    ("SLB", _("Solomon Islands") ),
    ("SOM", _("Somalia") ),
    ("ZAF", _("South Africa") ),
    ("SGS", _("South Georgia and the South Sandwich Islands") ),
    ("SSD", _("South Sudan") ),
    ("ESP", _("Spain") ),
    ("LKA", _("Sri Lanka") ),
    ("SDN", _("Sudan") ),
    ("SUR", _("Suriname") ),
    ("SJM", _("Svalbard and Jan Mayen") ),
    ("SWZ", _("Swaziland") ),
    ("SWE", _("Sweden") ),
    ("CHE", _("Switzerland") ),
    ("SYR", _("Syrian Arab Republic") ),
    ("TWN", _("Taiwan, Province of China") ),
    ("TJK", _("Tajikistan") ),
    ("TZA", _("Tanzania, United Republic of") ),
    ("THA", _("Thailand") ),
    ("TLS", _("Timor-Leste") ),
    ("TGO", _("Togo") ),
    ("TKL", _("Tokelau") ),
    ("TON", _("Tonga") ),
    ("TTO", _("Trinidad and Tobago") ),
    ("TUN", _("Tunisia") ),
    ("TUR", _("Turkey") ),
    ("TKM", _("Turkmenistan") ),
    ("TCA", _("Turks and Caicos Islands") ),
    ("TUV", _("Tuvalu") ),
    ("UGA", _("Uganda") ),
    ("UKR", _("Ukraine") ),
    ("ARE", _("United Arab Emirates") ),
    ("GBR", _("United Kingdom") ),
    ("USA", _("United States") ),
    ("UMI", _("United States Minor Outlying Islands") ),
    ("URY", _("Uruguay") ),
    ("UZB", _("Uzbekistan") ),
    ("VUT", _("Vanuatu") ),
    ("VEN", _("Venezuela, Bolivarian Republic of") ),
    ("VNM", _("Viet Nam") ),
    ("VGB", _("Virgin Islands, British") ),
    ("VIR", _("Virgin Islands, U.S.") ),
    ("WLF", _("Wallis and Futuna") ),
    ("ESH", _("Western Sahara") ),
    ("YEM", _("Yemen") ),
    ("ZMB", _("Zambia") ),
    ("ZWE", _("Zimbabwe") ),
)

