# Generated by Django 2.0.7 on 2018-07-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.DecimalField(decimal_places=2, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('Ex', 'Express'), ('Ec', 'Economy')], max_length=2)),
                ('transit', models.CharField(choices=[('Im', 'Import'), ('Ex', 'Export')], max_length=2)),
                ('document', models.BooleanField(default=False)),
                ('extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneNo', models.IntegerField(max_length=2)),
                ('economy', models.BooleanField(default=False)),
                ('express', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.Country')),
            ],
        ),
        migrations.AddField(
            model_name='tariff',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.Zone'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='international.Country'),
        ),
    ]
