# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipper_cite',
            field=models.CharField(max_length=100, verbose_name='shipper_cite'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper_name',
            field=models.CharField(max_length=100, verbose_name='shipper_name'),
        ),
    ]
