# Generated by Django 2.0.7 on 2018-07-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0002_auto_20180727_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_id',
            new_name='company',
        ),
    ]
